language: - node_js
node_js:
  - "12"

install: npm install
script:
  - npm run build
  - docker build -t imagename .   // `imagename`是变量，镜像的名字，你随便写个。特别注意，后面那个点是必须要的，不要写掉了！
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker push imagename   // `imagename`注释同上

  